language: cpp

sudo: false

compiler:
  - gcc

os:
  - linux

env:
  global:
    - secure: "0S91nn9WWYQH7yhyqyCNgdKbkA8wJY2VEszLYfmVhn82/gJvWR94iY0h5S7qctyJWU2C4ygGinQN6chnc8j2EPbPhmBWlU7/OIWiE5QimxysaRJdZ/rOoqECCQ+gLt4EeFDOVOeMUirOtaRsmFLg/GcSjJoeAxK2gaHvC904redoCohZjXHBj/UwSqhylYZhIwxzxSTrhHMsrY4te+1RdOAwNucCs99ZcdCgKCaO2llrfrvvHoTREk8eqxW+fYIJ731Sl2aYFRLi3zu3QQnkPLKjMMAM4Pa3sGK0/jnuigx72WARE18M1WnVesvOR26hnkBg+4TenZPk8VRelCIx4ZYZYlXoSzqegZZyMnt6t2f5wE5MxhlXSneM+Qg5iN76R98qMBm8C3TQbHfb/4xkzGbKX2TQJ+WBPHZqksDB6wKNubvDkcdKWFJQscnngPMZ9+LT3To5KwFI4U4DEGzHKvc6ViiOMCMe3obH+MMDxlox99pNta80XvRNvWvaPDIC8cN6RTkwR8+frDm3mWBFNYemBprXhksfARkZX48cI3rU3xtDyGI4wfu+9RfOtELsd5/HXWz0AtRHvIX8obe3F4iI4zh+gZeJUlKgaH6pt9WCqiOuVuj3YvH0DtQypzgtjlqoqybXNSIgyHOhzjhcS+GpIP6qyJnIMHfZ7/IhxUs="
    - secure: "L+qvZPBCsRs/ev4Aa35YosCl3ds/jFereVLLxSEUj4w6edaeOBKwEbwLiGy8JrYFXY6Q4fwjpH+gTbHXBGqP6lgNOYK84Ug6YnhPSnh/Xwtnlx+BKhBh0Go++z5r+3gAmPBoJxuzTZ2IzW29BgucxdK8Aee+/MMh+V2cd35ouOGS90fJP2yO2iDnqn5N2hfwkfA403WZ3WZVciQkTuSI32Uruj30YyhnY4ZfRXLI0x0GNvLd+2DLPgdhiMRs7jK+ITwqNt5Eg4CIQEDSeZ3gaKdqPtx1ioqs9Yr1vrdAYebc97W6jQ0QCMbmBxUoDTW6A4BpKQkr4EjbZlRkYdfHbxiiIbsgxqmxfvfvkkmUTSCCdtq51UZLvuixAEkLPgDDaQ0aRNeTSAie9viArAWtL9eH/RyqZG8We4epZEhXvRUZvEx0zfuPvza5RLR2V3B/9y2OxpVzSIaXhEnPRPij97MNIZrZ9h/GWOl9iO0yJMyLsMqv6dmkMKyThC3b0Ix+TTEpCjo2rPnpg44kCLSiaGd3ut0b/Z4wydl9MS89NrSluVoU61a/lZl19GHAGVOJ797RC03caK9zDq9dgGwBAu94G42svjdZd8D0ZueCMdyvDh/Mt4w71bQcgzhZ+UmmD5thBrv8KL/CnYFROBuULDm/4gy7dIBYdv8obRT1Uqw="

addons:
  apt:
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libasound2-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxinerama-dev
      - libxrandr-dev

  coverity_scan:
    project:
      name: "Marqin/godot"
    notification_email: "$COVERITY_SCAN_NOTIFICATION_EMAIL"
    build_command: "scons platform=x11 target=debug tools=yes"
    branch_pattern: "coverity_scan"


script:
  - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then echo "Something went wrong..."; fi
