language: cpp

sudo: false

compiler:
  - clang

os:
  - osx

env:
  - GODOT_TARGET=osx

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install scons llvm38; fi

script:
  - export CC_AN="$(dirname $(which scan-build))/"$(dirname $(readlink $(which scan-build)))"/../share/clang/tools/scan-build/libexec/ccc-analyzer"
  - export CXX_AN="$(dirname $(which scan-build))/"$(dirname $(readlink $(which scan-build)))"/../share/clang/tools/scan-build/libexec/c++-analyzer"
  - scan-build scons platform=osx tools=no CXX="$CXX_AN" CC="$CC_AN" -j 3
